Repository rewiringamerica/buildstockbatch, pull requests merged in 2023-11, with the labels that each got.

#4 Run building simulations on GCP Batch
  Dockerfile
  buildstockbatch/gcp/gcp.py
  setup.py
Labels: enhancement

#11 Add postprocessing support to GCP
  buildstockbatch/gcp/gcp.py
  buildstockbatch/postprocessing.py
  buildstockbatch/schemas/v0.3.yaml
Labels: enhancement

#13 Fix write path for postprocessing for GCP
  buildstockbatch/postprocessing.py
Labels: bug

#17 Fix GCP installation documentation cross-reference
  docs/installation.rst
Labels: documentation

#24 Make job_identifier actually optional
  buildstockbatch/gcp/gcp.py
Labels: bug

#21 Add support for running post-processing on GCP Cloud Run
  buildstockbatch/gcp/gcp.py
  buildstockbatch/schemas/v0.3.yaml
  docs/project_defn.rst
  setup.py
Labels: enhancement

#29 Skip post-processing of upgrade directories that fail to list
  buildstockbatch/postprocessing.py
Labels: bug

#34 Refactor docker_base to use inversion-of-control, and GCP to use that
  buildstockbatch/aws/aws.py
  buildstockbatch/cloud/docker_base.py
  buildstockbatch/gcp/gcp.py
  buildstockbatch/test/test_docker_base.py
Labels: enhancement

#37 Make post-processing wait until completion, then report stats
  buildstockbatch/gcp/gcp.py
Labels: enhancement
